---
- name: "venv | Ensure venv directory exists {{ venv.path }}"
  ansible.builtin.file:
    path: "{{ venv.path }}"
    state: directory
    mode: '0755'

- name: "venv | Create venv {{ venv.name }}"
  ansible.builtin.pip:
    name:
      - "pip"
      - "setuptools"
      - "wheel"
    extra_args: "{{ venv.extra_args | default(omit) }}"
    virtualenv: "{{ venv.path }}/{{ venv.name }}"
    virtualenv_python: "{{ venv.python | default(omit) }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

- name: "venv | Install packages in {{ venv.name }}"
  ansible.builtin.pip:
    name: "{{ venv.packages }}"
    extra_args: "{{ venv.extra_args | default(omit) }}"
    virtualenv: "{{ venv.path }}/{{ venv.name }}"
    virtualenv_python: "{{ venv.python | default(omit) }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when:
    - venv.packages is defined
    - venv.packages | length > 0
