---
- name: "Ensure venv directory {{ venv.path }}/{{ venv.name }} exists"
  ansible.builtin.file:
    path: "{{ venv.path }}"
    state: directory
    mode: '0755'

- name: "Create venv in {{ venv.path }}/{{ venv.name }} with {{ venv.python }}"
  ansible.builtin.pip:
    name:
      - "pip"
      - "setuptools"
      - "wheel"
    extra_args: "{{ venv.extra_args | default(omit) }}"
    virtualenv: "{{ venv.path }}/{{ venv.name }}"
    virtualenv_python: "{{ venv.python }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

- name: "Install packages in {{ venv.path }}/{{ venv.name }} with {{ venv.python }}"
  ansible.builtin.pip:
    name: "{{ venv.packages }}"
    extra_args: "{{ venv.extra_args | default(omit) }}"
    virtualenv: "{{ venv.path }}/{{ venv.name }}"
    virtualenv_python: "{{ venv.python }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when:
    - venv.packages is defined
    - venv.packages | length > 0
