---
molecule_exceptions:
  - variation: "amazonlinux"
    reason: "Interpreter Problems"
  - variation: "CentOS/RedHat 7"
    reason: "Interpreter Problems"
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current", "development"]
    platforms:
      - "debian9"
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos-stream8"
      - "centos-stream9"
      - "ubi8"
      - "fedora35"
      - "fedora36"
      - "rockylinux8"
      - "almalinux8"
