---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    python_pip_packages_map:
      Debian:
        "9":
          -"python-dateutil"
        "10":
          - "python-dateutil"
        "11":
          - "python-dateutil"
        # Debian bookworm python environment is externally managed
        "12":
          - ""
      default: "python-dateutil"
    # yamllint disable-line rule:line-length
    python_pip_packages: "{{ python_pip_os_packages_map[ansible_distribution][ansible_distribution_major_version] | default(python_pip_os_packages_map[ansible_distribution]) | default(python_pip_os_packages_map['default']) }}"

    python_pip_venvs:
      - name: "fullExample"
        python: "python"
        path: "/opt"
        packages:
          - "python-dateutil"
        extra_args: "--no-compile"
        state: latest
      - name: "minExample"
        python: "python"
        path: "/opt"
      - name: "mixExample"
        python: "python"
        path: "/opt"
        state: latest

  roles:
    - role: "ansible-role-python_pip"
